<p>
    <a href="<?php echo $this->url(array(), 'lekarz_index') ?>">
	<span style="margin-left: 60px;">Lista lekarzy</span>
    </a>
    <a href="<?php echo $this->url(array(), 'specjalizacja_index') ?>">
	<span style="margin-left: 40px;">Lista specjalizacji</span>
    </a>
</p>
<p>Lista lekarzy</p>
<ul>
    <?php foreach ($this->lekarze as $lekarz): ?>
        <li>
    	<a href="<?php echo $this->url(array('slug' => $lekarz['slug']), 'lekarz_show') ?>">
		<?php echo $lekarz; ?>
    	</a>
        </li>
    <?php endforeach; ?>
</ul>