<p>
    Imię: <?php echo $this->lekarz->imie; ?><br />
    Nazwisko: <?php echo $this->lekarz->nazwisko; ?><br />
    Nr gabinetu: <?php echo $this->lekarz->nr_gabinetu; ?><br />
    Specjalizacje: <br />
    <?php foreach ($this->lekarz->getSpecjalizacje() as $specjalizacja): ?>
        <span style="margin-left: 30px;">
    	<a href="<?php echo $this->url(array('slug' => $specjalizacja['slug']), 'specjalizacja_show') ?>">
		<?php echo $specjalizacja ?>
    	</a>
        </span><br />
    <?php endforeach; ?>
    Nr telefonu: <?php echo $this->lekarz->telefon; ?><br />
    Adres: <?php echo $this->lekarz->adres; ?><br />
    E-mail: <?php echo $this->lekarz->email; ?><br />
</p>
<p>
    <strong>Godziny przyjęć:</strong>
</p>
<table style="border-spacing: 20px 0px;">
    <thead>
	<tr>
	    <th>Dzień tygodnia</th>
	    <th>Od</th>
	    <th>Do</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ($this->lekarz->getGodzinyPrzyjec() as $godzina): ?>
    	<tr>
    	    <td><?php echo $godzina->dzien_tygodnia ?></td>
    	    <td><?php echo $godzina->czasBezSekund($godzina->godzina_od) ?></td>
    	    <td><?php echo $godzina->czasBezSekund($godzina->godzina_do) ?></td>
    	</tr>
	<?php endforeach; ?>
    </tbody>
</table>

<p style="text-align: right;">
    <a href="<?php echo $this->url(array(), 'lekarz_index') ?>">Powrót do listy</a>
</p>